"""Sweep pathway prevalence and mean-abundance filter thresholds under LODO CV.

Uses unstratified pathways only (data/raw/pathway_unstratified_full.csv,
generated by merge_pathways.py). Demonstrates that headline AUC is stable
across a wide range of filter settings.

Usage:
    python3 scripts/sensitivity_analysis.py
"""
import itertools, os, sys
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

sys.path.insert(0, os.path.dirname(__file__))
from lodo_cv import run_lodo_cv

PREVALENCE_GRID = [0.05, 0.10, 0.15, 0.20, 0.25]
MEAN_GRID = [1e-7, 1e-6, 1e-5, 1e-4]

def main():
    sp = pd.read_csv('data/processed/species_filtered.csv')
    pw_raw = pd.read_csv('data/raw/pathway_unstratified_full.csv')
    md = pd.read_csv('data/processed/metadata_clean.csv')

    joint = sp.merge(pw_raw, on='sample_id', suffixes=('_sp', '_pw'))
    mg = md.merge(joint, on='sample_id', how='inner')
    fc = [c for c in joint.columns if c != 'sample_id']

    import re
    def sanitize(c):
        return re.sub(r'[\[\]<>]', '_', c)

    mask = mg['label'].isin([0, 1])
    X = mg.loc[mask, fc].reset_index(drop=True)
    X.columns = [sanitize(c) for c in X.columns]
    sp_feat_cols = [sanitize(c) for c in sp.columns if c != 'sample_id']
    pw_feat_cols = [sanitize(c) for c in pw_raw.columns if c != 'sample_id']

    y = mg.loc[mask, 'label'].reset_index(drop=True)
    meta = mg.loc[mask, ['sample_id', 'study_name', 'study_condition', 'label']].reset_index(drop=True)

    assert len(X) == 646, f'Expected 646 CRC+healthy samples, got {len(X)}'
    assert len(sp_feat_cols) == 247, f'Expected 247 species features, got {len(sp_feat_cols)}'

    rows = []
    combos = list(itertools.product(PREVALENCE_GRID, MEAN_GRID))
    for i, (prev_thresh, mean_thresh) in enumerate(combos, 1):
        print(f'\n[{i}/{len(combos)}] prevalence >= {prev_thresh}, mean >= {mean_thresh}')

        def pathway_filter(X_train, _pt=prev_thresh, _mt=mean_thresh):
            Xpw = X_train[pw_feat_cols]
            prev = (Xpw > 0).mean(axis=0)
            ma = Xpw.mean(axis=0)
            keep_pw = [c for c in pw_feat_cols
                       if prev[c] >= _pt and ma[c] >= _mt]
            return sp_feat_cols + keep_pw

        def make_rf():
            return RandomForestClassifier(n_estimators=500, max_features='sqrt',
                min_samples_leaf=5, n_jobs=-1, random_state=42,
                class_weight='balanced')

        res = run_lodo_cv(make_rf, X, y, meta, feature_filter_fn=pathway_filter)
        assert len(res['auc']) == 7, f'Expected 7 folds, got {len(res["auc"])}'
        rows.append({
            'prevalence_threshold': prev_thresh,
            'mean_threshold': mean_thresh,
            'mean_auc': res['mean_auc'],
            'std_auc': res['std_auc'],
            'min_features': min(res['n_features']),
            'max_features': max(res['n_features']),
        })

    df = pd.DataFrame(rows)
    os.makedirs('results', exist_ok=True)
    df.to_csv('results/sensitivity_thresholds.csv', index=False)
    print(f'\nSaved results/sensitivity_thresholds.csv')
    print(f'AUC range: {df["mean_auc"].min():.3f} - {df["mean_auc"].max():.3f} '
          f'(spread = {df["mean_auc"].max() - df["mean_auc"].min():.3f})')

if __name__ == '__main__':
    main()
